# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-30 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('eamil', models.EmailField(max_length=200, verbose_name='邮箱')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
        ),
    ]
