# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-24 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=230, unique=True, verbose_name='邮箱')),
            ],
        ),
    ]
