# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-26 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laoshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='名字')),
                ('age', models.CharField(max_length=8, unique=True, verbose_name='年龄')),
            ],
        ),
    ]
